[2025-01-20T09:54:43.490+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-20T09:54:43.503+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cryptobot_workflow.load_data manual__2025-01-20T09:52:27.088608+00:00 [queued]>
[2025-01-20T09:54:43.510+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cryptobot_workflow.load_data manual__2025-01-20T09:52:27.088608+00:00 [queued]>
[2025-01-20T09:54:43.510+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-20T09:54:43.519+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): load_data> on 2025-01-20 09:52:27.088608+00:00
[2025-01-20T09:54:43.530+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=145) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-20T09:54:43.540+0000] {standard_task_runner.py:72} INFO - Started process 146 to run task
[2025-01-20T09:54:43.544+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cryptobot_workflow', 'load_data', 'manual__2025-01-20T09:52:27.088608+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/cryptobot_dag.py', '--cfg-path', '/tmp/tmpcmahiwoj']
[2025-01-20T09:54:43.546+0000] {standard_task_runner.py:105} INFO - Job 64: Subtask load_data
[2025-01-20T09:54:44.224+0000] {task_command.py:467} INFO - Running <TaskInstance: cryptobot_workflow.load_data manual__2025-01-20T09:52:27.088608+00:00 [running]> on host 03c752f9c1ed
[2025-01-20T09:54:44.288+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cryptobot_workflow' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T09:52:27.088608+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-20T09:52:27.088608+00:00'
[2025-01-20T09:54:44.289+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-20T09:54:44.290+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-20T09:54:44.290+0000] {logging_mixin.py:190} INFO - Current task name:load_data state:running start_date:2025-01-20 09:54:43.503926+00:00
[2025-01-20T09:54:44.291+0000] {logging_mixin.py:190} INFO - Dag name:cryptobot_workflow and current dag run status:running
[2025-01-20T09:54:44.291+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-20T09:54:44.293+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-20T09:54:44.294+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/src/load.py']
[2025-01-20T09:54:44.308+0000] {subprocess.py:99} INFO - Output:
[2025-01-20T09:54:45.233+0000] {subprocess.py:106} INFO - Error connecting to MongoDB for insertion: [Errno 2] No such file or directory: '/opt/***/src/../data/data_processed'
[2025-01-20T09:54:45.850+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-20T09:54:46.056+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-20T09:54:46.063+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cryptobot_workflow, task_id=load_data, run_id=manual__2025-01-20T09:52:27.088608+00:00, execution_date=20250120T095227, start_date=20250120T095443, end_date=20250120T095446
[2025-01-20T09:54:46.112+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-20T09:54:46.116+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-20T09:54:46.118+0000] {logging_mixin.py:190} INFO - Dag name:cryptobot_workflow queued_at:2025-01-20 09:52:27.131769+00:00
[2025-01-20T09:54:46.121+0000] {logging_mixin.py:190} INFO - Task hostname:03c752f9c1ed operator:BashOperator
[2025-01-20T09:54:46.225+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-20T09:54:48.481+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-20T09:54:48.491+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-20T09:54:48.547+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
