[2025-01-20T09:54:59.821+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-20T09:54:59.842+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cryptobot_workflow.model_prediction manual__2025-01-20T09:52:27.088608+00:00 [queued]>
[2025-01-20T09:54:59.850+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cryptobot_workflow.model_prediction manual__2025-01-20T09:52:27.088608+00:00 [queued]>
[2025-01-20T09:54:59.854+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-20T09:54:59.878+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): model_prediction> on 2025-01-20 09:52:27.088608+00:00
[2025-01-20T09:54:59.890+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cryptobot_workflow', 'model_prediction', 'manual__2025-01-20T09:52:27.088608+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/cryptobot_dag.py', '--cfg-path', '/tmp/tmpm9umap4_']
[2025-01-20T09:54:59.891+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask model_prediction
[2025-01-20T09:54:59.887+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=151) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-20T09:54:59.892+0000] {standard_task_runner.py:72} INFO - Started process 152 to run task
[2025-01-20T09:55:00.835+0000] {task_command.py:467} INFO - Running <TaskInstance: cryptobot_workflow.model_prediction manual__2025-01-20T09:52:27.088608+00:00 [running]> on host 03c752f9c1ed
[2025-01-20T09:55:00.940+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cryptobot_workflow' AIRFLOW_CTX_TASK_ID='model_prediction' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T09:52:27.088608+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-20T09:52:27.088608+00:00'
[2025-01-20T09:55:00.944+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-20T09:55:00.945+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-20T09:55:00.945+0000] {logging_mixin.py:190} INFO - Current task name:model_prediction state:running start_date:2025-01-20 09:54:59.843066+00:00
[2025-01-20T09:55:00.945+0000] {logging_mixin.py:190} INFO - Dag name:cryptobot_workflow and current dag run status:running
[2025-01-20T09:55:00.948+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-20T09:55:00.953+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-20T09:55:00.957+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/src/predictions.py']
[2025-01-20T09:55:00.970+0000] {subprocess.py:99} INFO - Output:
[2025-01-20T09:55:01.220+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-01-20T09:55:01.222+0000] {subprocess.py:106} INFO -   File "/opt/***/src/predictions.py", line 2, in <module>
[2025-01-20T09:55:01.224+0000] {subprocess.py:106} INFO -     import joblib
[2025-01-20T09:55:01.224+0000] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'joblib'
[2025-01-20T09:55:01.227+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-01-20T09:55:01.298+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-20T09:55:01.308+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-20T09:55:01.309+0000] {logging_mixin.py:190} INFO - Task start:2025-01-20 09:54:59.843066+00:00 end:2025-01-20 09:55:01.307378+00:00 duration:1.464312
[2025-01-20T09:55:01.309+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): model_prediction> dag:<DAG: cryptobot_workflow> dagrun:<DagRun cryptobot_workflow @ 2025-01-20 09:52:27.088608+00:00: manual__2025-01-20T09:52:27.088608+00:00, state:running, queued_at: 2025-01-20 09:52:27.131769+00:00. externally triggered: True>
[2025-01-20T09:55:01.310+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-01-20T09:55:01.311+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=cryptobot_workflow, task_id=model_prediction, run_id=manual__2025-01-20T09:52:27.088608+00:00, execution_date=20250120T095227, start_date=20250120T095459, end_date=20250120T095501
[2025-01-20T09:55:01.339+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-20T09:55:01.340+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 65 for task model_prediction (Bash command failed. The command returned a non-zero exit code 1.; 152)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-20T09:55:01.402+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-20T09:55:03.834+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-20T09:55:03.848+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
