[2025-01-20T10:00:54.669+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-20T10:00:54.681+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cryptobot_workflow.model_prediction manual__2025-01-20T10:00:01.735068+00:00 [queued]>
[2025-01-20T10:00:54.686+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cryptobot_workflow.model_prediction manual__2025-01-20T10:00:01.735068+00:00 [queued]>
[2025-01-20T10:00:54.687+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-20T10:00:55.018+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): model_prediction> on 2025-01-20 10:00:01.735068+00:00
[2025-01-20T10:00:55.028+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=296) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-20T10:00:55.031+0000] {standard_task_runner.py:72} INFO - Started process 297 to run task
[2025-01-20T10:00:55.031+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cryptobot_workflow', 'model_prediction', 'manual__2025-01-20T10:00:01.735068+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/cryptobot_dag.py', '--cfg-path', '/tmp/tmpk4mtgtk2']
[2025-01-20T10:00:55.033+0000] {standard_task_runner.py:105} INFO - Job 70: Subtask model_prediction
[2025-01-20T10:00:55.099+0000] {task_command.py:467} INFO - Running <TaskInstance: cryptobot_workflow.model_prediction manual__2025-01-20T10:00:01.735068+00:00 [running]> on host 03c752f9c1ed
[2025-01-20T10:00:55.169+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cryptobot_workflow' AIRFLOW_CTX_TASK_ID='model_prediction' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T10:00:01.735068+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-20T10:00:01.735068+00:00'
[2025-01-20T10:00:55.171+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-20T10:00:55.172+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-20T10:00:55.173+0000] {logging_mixin.py:190} INFO - Current task name:model_prediction state:running start_date:2025-01-20 10:00:54.681988+00:00
[2025-01-20T10:00:55.173+0000] {logging_mixin.py:190} INFO - Dag name:cryptobot_workflow and current dag run status:running
[2025-01-20T10:00:55.173+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-20T10:00:55.174+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-20T10:00:55.175+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/src/predictions.py']
[2025-01-20T10:00:55.184+0000] {subprocess.py:99} INFO - Output:
[2025-01-20T10:00:56.946+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-01-20T10:00:56.970+0000] {subprocess.py:106} INFO -   File "/opt/***/src/predictions.py", line 7, in <module>
[2025-01-20T10:00:56.973+0000] {subprocess.py:106} INFO -     from sklearn.preprocessing import MinMaxScaler
[2025-01-20T10:00:56.974+0000] {subprocess.py:106} INFO - ModuleNotFoundError: No module named 'sklearn'
[2025-01-20T10:00:57.406+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-01-20T10:00:57.520+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-20T10:00:57.549+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-20T10:00:57.550+0000] {logging_mixin.py:190} INFO - Task start:2025-01-20 10:00:54.681988+00:00 end:2025-01-20 10:00:57.544811+00:00 duration:2.862823
[2025-01-20T10:00:57.552+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): model_prediction> dag:<DAG: cryptobot_workflow> dagrun:<DagRun cryptobot_workflow @ 2025-01-20 10:00:01.735068+00:00: manual__2025-01-20T10:00:01.735068+00:00, state:running, queued_at: 2025-01-20 10:00:01.817244+00:00. externally triggered: True>
[2025-01-20T10:00:57.553+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-01-20T10:00:57.555+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=cryptobot_workflow, task_id=model_prediction, run_id=manual__2025-01-20T10:00:01.735068+00:00, execution_date=20250120T100001, start_date=20250120T100054, end_date=20250120T100057
[2025-01-20T10:00:57.622+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-20T10:00:57.624+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 70 for task model_prediction (Bash command failed. The command returned a non-zero exit code 1.; 297)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-20T10:00:57.683+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-20T10:00:57.782+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-20T10:00:57.788+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
